"""
Phase 7D — shared report mapping, wording, and lint utilities.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

REPORT_VERSION = "7d.1.0"
PROJECT_NAME = "FASSD"
DECISION_LAYER_VERSION = "phase7c4_v2"
ANALYSIS_PROFILE = "pct_vote_0.65_0.70_vad40"
CHUNK_SPOOF_THRESHOLD = 0.65
MAX_SUSPICIOUS_SEGMENTS = 5

MANDATORY_DISCLAIMER = (
    "**Disclaimer:** This report was generated by the FASSD forensic decision-support prototype. "
    "It combines automated acoustic models, chunk-level scores, and rule-based calibration outputs. "
    "It is intended to **assist** human review only and must **not** be treated as the sole basis for "
    "legal, disciplinary, employment, or law-enforcement action. Results do not constitute proof of "
    "authenticity, deception, identity, or intent. A qualified reviewer should evaluate the original "
    "recording, context, and chain of custody before any consequential decision."
)

MANDATORY_LIMITATIONS: list[str] = [
    "This is a decision-support prototype, not a certified or market-validated forensic product.",
    "Final statuses come from Phase 7C4-v2 fusion rules over multiple model outputs, not a single classifier.",
    "On the Phase 7C1 controlled set, most nominally clean human files were classified as borderline (manual review), not automatically accepted.",
    "File-level direct-AI detection is not fully solved; segment-level evidence is used when file-level scores are weak.",
    "Models and rules were primarily evaluated on controlled Phase 7C1 and Phase 7A test suites, not all real-world channels.",
    "Outputs must not be presented as legal proof, court-ready conclusions, or guaranteed detection.",
    "High-stakes use requires manual expert review of audio and metadata.",
    "More external, multi-device, multi-language, and platform-compressed data is needed before broad deployment claims.",
    "Multiclass attack hints are auxiliary and may be unreliable on processed or replayed audio.",
    "Compression, noise, and recording chain strongly affect scores; environmental features are indicative only.",
]

FORBIDDEN_PHRASES: list[str] = [
    "definitely fake",
    "proven fake",
    "proves fake",
    "100% real",
    "100% fake",
    "court-ready",
    "guaranteed detection",
    "guaranteed",
    "legal proof",
    "confirms deception",
    "speaker is lying",
    "proves the speaker",
    "deepfake confirmed",
]

STATUS_SPECIFIC_LIMITATIONS: dict[str, str] = {
    "clean_human_borderline": "Borderline means conflicting evidence; the file must not be labeled synthetic without expert listen.",
    "clean_human_false_alarm": "Known false-alarm risk on clean human speech under current thresholds.",
    "direct_ai_file_level_missed_but_segment_suspicious": "File-level pooled vote may be REAL while segments remain suspicious—review timeline.",
    "partial_fabrication_not_evaluable": "Partial-region metrics were not computed due to missing or invalid suspicious timestamps.",
    "partial_fabrication_missed": "Partial fabrication may be present but not detected under current chunk rules.",
}

REQUIRED_JSON_KEYS: list[str] = [
    "report_id",
    "report_version",
    "project_name",
    "analysis_timestamp",
    "input_audio_path",
    "audio_filename",
    "audio_duration_s",
    "sample_rate_hz",
    "channels",
    "analysis_profile",
    "decision_layer_version",
    "overall_risk_level",
    "overall_status",
    "origin_hint",
    "manipulation_hint",
    "attack_hint",
    "manual_review_required",
    "confidence_level",
    "confidence_explanation",
    "file_level_evidence",
    "chunk_level_evidence",
    "segment_level_evidence",
    "model_agreement",
    "model_disagreement",
    "selected_model_evidence",
    "suspicious_segments",
    "executive_summary",
    "technical_summary",
    "evidence_summary",
    "recommended_action",
    "limitations",
    "disclaimer",
    "technical_traceability",
]

MARKDOWN_REQUIRED_SECTIONS: list[str] = [
    "## 1. Report Header",
    "## 2. Audio Metadata",
    "## 3. Executive Summary",
    "## 4. Final Risk Assessment",
    "## 5. Origin and Manipulation Hints",
    "## 6. Evidence Table",
    "## 7. Suspicious Segment Analysis",
    "## 8. Model Agreement / Disagreement",
    "## 9. Recommended Human Review Actions",
    "## 10. Limitations",
    "## 11. Disclaimer",
    "## 12. Technical Traceability Appendix",
]

CONFIDENCE_EXPLANATIONS: dict[str, str] = {
    "low": "Evidence is near thresholds, conflicting between models, or category-specific false-alarm risk applies.",
    "medium": "Category signal is present but segment-only or disagreement limits certainty.",
    "high": "Multiple indicators align under the controlled test profile; still not legal proof.",
}


@dataclass(frozen=True)
class StatusMapping:
    overall_risk_level: str
    overall_status: str
    origin_hint: str
    manipulation_hint: str
    manual_review_required: bool
    confidence_level: str
    executive_wording: str
    recommended_action: str | None = None


STATUS_MAP: dict[str, StatusMapping] = {
    "clean_human_accepted": StatusMapping(
        "low",
        "no_strong_synthetic_or_manipulation_evidence",
        "likely_human",
        "no_strong_manipulation_evidence",
        False,
        "medium",
        "No strong synthetic or manipulation evidence was detected under the current analysis settings.",
        "Optional routine review per organizational policy; retain original file and metadata.",
    ),
    "clean_human_borderline": StatusMapping(
        "medium",
        "inconclusive_manual_review_recommended",
        "likely_human_or_uncertain",
        "uncertain",
        True,
        "low",
        "The file contains conflicting evidence. Some model outputs suggest low risk, while segment-level indicators require manual review.",
        None,
    ),
    "clean_human_false_alarm": StatusMapping(
        "medium",
        "suspicious_but_possible_clean_human_false_alarm",
        "uncertain",
        "uncertain",
        True,
        "low",
        "The system flagged suspicious evidence, but this category has known false-alarm risk on clean human speech. Manual review is required.",
        None,
    ),
    "direct_ai_detected": StatusMapping(
        "high",
        "ai_synthetic_speech_indicators_detected",
        "likely_ai_generated",
        "synthetic_generation_indicators",
        True,
        "high",
        "The system detected indicators consistent with AI-generated or synthetic speech at the file level. Manual review is required.",
        None,
    ),
    "direct_ai_file_level_missed_but_segment_suspicious": StatusMapping(
        "high",
        "segment_level_ai_suspicion",
        "ai_suspicious",
        "synthetic_segment_indicators",
        True,
        "medium",
        "File-level pooled scores did not reach the detection threshold, but segment-level evidence indicates possible synthetic speech in one or more regions.",
        None,
    ),
    "direct_ai_missed": StatusMapping(
        "medium",
        "evaluation_mismatch_or_weak_ai_evidence",
        "uncertain",
        "uncertain",
        True,
        "low",
        "Under current settings, strong AI indicators were not assigned; expert review is recommended if context expects synthetic speech.",
        None,
    ),
    "human_replay_manipulation_detected": StatusMapping(
        "medium",
        "replay_or_rerecording_indicators_detected",
        "likely_human",
        "replayed_or_rerecorded",
        True,
        "medium",
        "Speech content appears consistent with human origin, with indicators of replay or re-recording. This does not by itself indicate AI synthesis.",
        None,
    ),
    "human_replay_missed": StatusMapping(
        "medium",
        "replay_evidence_weak_or_missed",
        "likely_human_or_uncertain",
        "uncertain",
        True,
        "low",
        "Replay or re-recording indicators were weak or not assigned under current settings.",
        None,
    ),
    "ai_replay_detected": StatusMapping(
        "high",
        "ai_replay_or_processed_speech_indicators_detected",
        "ai_suspicious",
        "replayed_or_rerecorded",
        True,
        "high",
        "Indicators suggest AI-related speech content combined with replay or re-recording / channel effects. Manual review is required.",
        None,
    ),
    "ai_replay_file_level_missed_but_segment_suspicious": StatusMapping(
        "high",
        "segment_level_ai_replay_suspicion",
        "ai_suspicious",
        "replayed_or_rerecorded",
        True,
        "medium",
        "File-level scores were borderline, but segment-level evidence suggests AI-related speech with replay or channel effects.",
        None,
    ),
    "ai_replay_missed": StatusMapping(
        "medium",
        "ai_replay_evidence_weak_or_missed",
        "uncertain",
        "uncertain",
        True,
        "low",
        "AI replay indicators were weak or not assigned under current settings.",
        None,
    ),
    "human_mixer_manipulation_detected": StatusMapping(
        "medium",
        "channel_processing_or_mixer_artifacts_detected",
        "likely_human",
        "channel_processed",
        True,
        "medium",
        "The system detected indicators of channel processing or mixer-like artifacts on likely human-origin speech.",
        None,
    ),
    "human_mixer_missed": StatusMapping(
        "medium",
        "mixer_evidence_weak_or_missed",
        "likely_human_or_uncertain",
        "uncertain",
        True,
        "low",
        "Mixer or channel-processing indicators were weak or not assigned under current settings.",
        None,
    ),
    "ai_mixer_detected": StatusMapping(
        "high",
        "ai_speech_with_channel_processing_indicators",
        "ai_suspicious",
        "channel_processed",
        True,
        "high",
        "Indicators suggest AI-related speech with channel processing or mixer-like artifacts. Manual review is required.",
        None,
    ),
    "ai_mixer_file_level_missed_but_segment_suspicious": StatusMapping(
        "high",
        "segment_level_ai_mixer_suspicion",
        "ai_suspicious",
        "channel_processed",
        True,
        "medium",
        "Segment-level evidence suggests AI-related speech with channel or mixer artifacts; file-level scores were borderline.",
        None,
    ),
    "ai_mixer_missed": StatusMapping(
        "medium",
        "ai_mixer_evidence_weak_or_missed",
        "uncertain",
        "uncertain",
        True,
        "low",
        "AI mixer indicators were weak or not assigned under current settings.",
        None,
    ),
    "partial_fabrication_detected": StatusMapping(
        "high",
        "partial_fabrication_or_splice_indicators_detected",
        "mixed_or_uncertain",
        "edited_or_partially_synthetic",
        True,
        "high",
        "Segment-level evidence suggests possible partial fabrication or inserted content. Review flagged time ranges.",
        None,
    ),
    "partial_fabrication_missed": StatusMapping(
        "medium",
        "no_strong_partial_fabrication_evidence_but_limitations_apply",
        "mixed_or_uncertain",
        "uncertain",
        True,
        "low",
        "Strong partial-fabrication indicators were not detected under current settings; limitations apply if editing is suspected from external context.",
        None,
    ),
    "partial_fabrication_not_evaluable": StatusMapping(
        "inconclusive",
        "partial_fabrication_not_evaluable_missing_timestamps",
        "uncertain",
        "uncertain",
        True,
        "low",
        "Partial-fabrication region evaluation requires valid suspicious start/end times; manual review is required.",
        None,
    ),
    "borderline_needs_review": StatusMapping(
        "inconclusive",
        "inconclusive_manual_review_recommended",
        "uncertain",
        "uncertain",
        True,
        "low",
        "The file requires manual review under current calibration rules.",
        None,
    ),
    "unknown_review_required": StatusMapping(
        "inconclusive",
        "unknown_review_required",
        "uncertain",
        "uncertain",
        True,
        "low",
        "The file could not be classified confidently; manual review is required.",
        None,
    ),
}

FALLBACK_MAPPING = STATUS_MAP["unknown_review_required"]

RISK_DEFAULT_ACTIONS: dict[str, str] = {
    "low": "Optional routine review per policy; retain original file and metadata.",
    "medium": "Manual listen; compare segment timeline; do not use as sole accusatory evidence.",
    "high": "Priority manual review; document chain of custody; consider independent expert.",
    "inconclusive": "Do not automate decision; obtain missing metadata or re-analyze with valid partial timestamps.",
}


def _f(val: Any) -> float | None:
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return None
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def _s(val: Any) -> str:
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return ""
    return str(val).strip()


def map_status(calibrated_status: str, suspicious_chunk_ratio: float | None) -> StatusMapping:
    st = _s(calibrated_status) or "unknown_review_required"
    m = STATUS_MAP.get(st, FALLBACK_MAPPING)
    if st == "human_replay_manipulation_detected" and suspicious_chunk_ratio is not None:
        if suspicious_chunk_ratio >= 0.5:
            return StatusMapping(
                "high",
                m.overall_status,
                m.origin_hint,
                m.manipulation_hint,
                m.manual_review_required,
                m.confidence_level,
                m.executive_wording,
                m.recommended_action,
            )
    if st == "human_mixer_manipulation_detected" and suspicious_chunk_ratio is not None:
        if suspicious_chunk_ratio >= 0.5:
            return StatusMapping(
                "high",
                m.overall_status,
                m.origin_hint,
                m.manipulation_hint,
                m.manual_review_required,
                m.confidence_level,
                m.executive_wording,
                m.recommended_action,
            )
    return m


def attack_hint_from_baseline(row: pd.Series | None) -> str:
    if row is None:
        return "unknown"
    at = _s(row.get("attack_type")).lower()
    if at == "bonafide":
        return "bonafide"
    if at == "synthesis":
        return "synthesis"
    if at == "conversion":
        return "voice_conversion"
    if at == "replay":
        return "replay"
    return "unknown"


def load_indexed_csv(path: Path | None, id_col: str = "sample_id") -> dict[str, pd.Series]:
    if path is None or not path.is_file():
        return {}
    df = pd.read_csv(path, low_memory=False)
    if id_col not in df.columns:
        return {}
    out: dict[str, pd.Series] = {}
    for _, row in df.iterrows():
        out[_s(row[id_col])] = row
    return out


def load_error_ids(path: Path | None) -> set[str]:
    if path is None or not path.is_file():
        return set()
    df = pd.read_csv(path, low_memory=False)
    col = "sample_id" if "sample_id" in df.columns else df.columns[0]
    return {_s(x) for x in df[col].tolist() if _s(x)}


def find_chunk_timeline(chunk_dir: Path | None, sample_id: str) -> Path | None:
    if chunk_dir is None or not chunk_dir.is_dir():
        return None
    for pattern in (f"{sample_id}_chunks.csv", f"{sample_id}.csv"):
        p = chunk_dir / pattern
        if p.is_file():
            return p
    matches = list(chunk_dir.glob(f"{sample_id}*chunks*.csv"))
    return matches[0] if matches else None


def load_chunk_timeline(path: Path | None) -> pd.DataFrame:
    if path is None or not path.is_file():
        return pd.DataFrame()
    return pd.read_csv(path, low_memory=False)


def estimate_duration_s(chunks: pd.DataFrame, baseline: pd.Series | None) -> float | None:
    if not chunks.empty and "end_time" in chunks.columns:
        return float(chunks["end_time"].max())
    if baseline is not None:
        st = _f(baseline.get("suspicious_end_time"))
        if st is not None:
            return st + 4.0
    return None


def build_suspicious_segments(
    *,
    sample_id: str,
    chunks: pd.DataFrame,
    partial_row: pd.Series | None,
    calibrated_status: str,
) -> list[dict[str, Any]]:
    segments: list[dict[str, Any]] = []
    seen: set[tuple[float, float]] = set()

    def add(seg: dict[str, Any]) -> None:
        key = (round(float(seg["start_time"]), 2), round(float(seg["end_time"]), 2))
        if key in seen:
            return
        seen.add(key)
        segments.append(seg)

    if partial_row is not None:
        ps = _f(partial_row.get("suspicious_start_time"))
        pe = _f(partial_row.get("suspicious_end_time"))
        if ps is not None and pe is not None and pe > ps:
            inside_max = _f(partial_row.get("inside_region_max_spoof"))
            add(
                {
                    "start_time": ps,
                    "end_time": pe,
                    "segment_type": "labeled_partial_region",
                    "evidence_score": inside_max if inside_max is not None else 0.0,
                    "evidence_source": "baseline",
                    "explanation": "Labeled suspicious region for partial-fabrication evaluation; inside-region scores exceed outside baseline where detected.",
                    "review_priority": "high",
                }
            )

    if not chunks.empty and "spoof_probability" in chunks.columns:
        sub = chunks.copy()
        sub["spoof_probability"] = pd.to_numeric(sub["spoof_probability"], errors="coerce")
        sub = sub.dropna(subset=["spoof_probability"])
        sub = sub.sort_values("spoof_probability", ascending=False)
        for _, ch in sub.head(MAX_SUSPICIOUS_SEGMENTS * 2).iterrows():
            score = float(ch["spoof_probability"])
            if score < CHUNK_SPOOF_THRESHOLD:
                continue
            st = float(ch.get("start_time", 0))
            en = float(ch.get("end_time", st + 4))
            priority = "high" if score >= 0.85 else "medium"
            add(
                {
                    "start_time": st,
                    "end_time": en,
                    "segment_type": "high_spoof_chunk",
                    "evidence_score": score,
                    "evidence_source": "baseline",
                    "explanation": "Segment-level evidence indicates elevated spoof-like scores in this window; manual review is recommended.",
                    "review_priority": priority,
                }
            )
            if len(segments) >= MAX_SUSPICIOUS_SEGMENTS:
                break

    if "segment" in calibrated_status and len(segments) == 0:
        add(
            {
                "start_time": 0.0,
                "end_time": 4.0,
                "segment_type": "high_spoof_chunk",
                "evidence_score": 0.0,
                "evidence_source": "fused",
                "explanation": "Segment-level suspicion was assigned without chunk timeline export; expert review of the full file is recommended.",
                "review_priority": "medium",
            }
        )

    return segments[:MAX_SUSPICIOUS_SEGMENTS]


def model_disagreement_flags(
    baseline_status: str,
    r2_p_status: str,
    r2_l_status: str,
    baseline_score: float | None,
    r2_p_score: float | None,
) -> list[str]:
    flags: list[str] = []
    if baseline_status and r2_p_status and baseline_status != r2_p_status:
        flags.append("baseline_vs_r2_product_status_mismatch")
    if baseline_score is not None and r2_p_score is not None:
        if baseline_score >= 0.65 and r2_p_score < 0.5:
            flags.append("baseline_high_r2_low_file")
        if baseline_score < 0.5 and r2_p_score >= 0.65:
            flags.append("baseline_low_r2_high_file")
    if r2_p_status and r2_l_status and r2_p_status != r2_l_status:
        flags.append("r2_product_vs_r2_loss_mismatch")
    return flags


def build_limitations(calibrated_status: str, is_error_case: bool) -> list[str]:
    lims = list(MANDATORY_LIMITATIONS)
    extra = STATUS_SPECIFIC_LIMITATIONS.get(calibrated_status)
    if extra:
        lims.append(extra)
    if is_error_case:
        lims.append(
            "This file was flagged in the Phase 7C4-v2 internal error-case set; treat conclusions with extra caution."
        )
    return lims


def collect_narrative_lint_text(report: dict[str, Any]) -> str:
    """Narrative fields only — exclusions/limitations may quote forbidden terms in negation."""
    parts = [
        report.get("executive_summary", ""),
        report.get("technical_summary", ""),
        report.get("evidence_summary", ""),
        report.get("recommended_action", ""),
    ]
    fl = report.get("file_level_evidence") or {}
    parts.append(fl.get("summary", ""))
    ma = report.get("model_agreement") or {}
    parts.append(ma.get("agreement_summary", ""))
    md = report.get("model_disagreement") or {}
    parts.append(md.get("summary", ""))
    for seg in report.get("suspicious_segments") or []:
        parts.append(seg.get("explanation", ""))
    return "\n".join(str(p) for p in parts if p)


def lint_report_text(text: str, *, check_disclaimer: bool = False) -> list[str]:
    issues: list[str] = []
    lower = text.lower()
    for phrase in FORBIDDEN_PHRASES:
        if phrase in lower:
            issues.append(f"forbidden_phrase:{phrase}")
    if check_disclaimer and "decision-support prototype" not in lower:
        issues.append("missing_mandatory_disclaimer")
    return issues


def lint_full_report(report: dict[str, Any]) -> list[str]:
    issues = lint_report_text(collect_narrative_lint_text(report))
    issues.extend(lint_report_text(report.get("disclaimer", ""), check_disclaimer=True))
    risk = report.get("overall_risk_level")
    if risk in ("medium", "high", "inconclusive") and not report.get("manual_review_required"):
        issues.append("manual_review_required_false_for_elevated_risk")
    st = report.get("technical_traceability", {}).get("phase7c4_status", "")
    if st == "clean_human_borderline":
        exec_s = report.get("executive_summary", "").lower()
        if re.search(r"\b(is|are)\s+fake\b", exec_s) or "ai-generated speech" in exec_s and "not" not in exec_s:
            issues.append("borderline_described_as_fake")
    if st == "direct_ai_file_level_missed_but_segment_suspicious":
        tech = report.get("technical_summary", "").lower()
        if "file-level proof" in tech or "proven at file level" in tech:
            issues.append("segment_case_claims_file_level_proof")
    if st == "human_replay_manipulation_detected":
        exec_s = report.get("executive_summary", "").lower()
        if "ai-generated" in exec_s and "does not" not in exec_s and "not by itself" not in exec_s:
            issues.append("human_replay_claims_ai_generated")
    if st == "partial_fabrication_detected":
        segs = report.get("suspicious_segments") or []
        seg_ev = report.get("segment_level_evidence") or {}
        has_partial = seg_ev.get("labeled_suspicious_start_s") is not None or any(
            s.get("segment_type") == "labeled_partial_region" for s in segs
        )
        if not has_partial and seg_ev.get("partial_region_detected") is True:
            issues.append("partial_detected_missing_segment_info")
    return issues


def iso_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
